FixIt/Controllers/AdminController.cs
using FixIt.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FixIt.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class AdminController : Controller
    {
        private readonly UserManager<IdentityUser> usermanager;
        public AdminController(UserManager<IdentityUser> _usermanager)
        {
            usermanager = _usermanager;
        }
        public async Task<IActionResult> Index()
        {
            var admins = (await usermanager
                .GetUsersInRoleAsync("Administrator"))
                .ToArray();

            var everyone = await usermanager.Users.ToArrayAsync();

            var model = new AdminViewModel
            {
                Administrators = admins,
                Everyone = everyone
            };

            return View(model);
        }
    }
}

FixIt/Controllers/FixItController.cs
using FixIt.Models;
using FixIt.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FixIt.Controllers
{
    [Authorize]
    public class FixItController : Controller
    {
        private readonly IFixItService fixitService;
        private readonly UserManager<IdentityUser> usermanager;
        public FixItController(IFixItService _fixitService, UserManager<IdentityUser> _usermanager)
        {
            fixitService = _fixitService;
            usermanager = _usermanager;
        }
        public async Task<IActionResult> Index()
        {
            // hämta påloggad user
            var currentuser = await usermanager.GetUserAsync(User);
            // hämta todo items
            var items = await fixitService.GetIncompleteAsync(currentuser);
            //Skicka items till en modell
            var model = new ToDoViewModel()
            {
                Items = items
        };
            //Skicka resultatet till en view
            return View(model);
        }
        public async Task<IActionResult> AddItem(ToDoItem newitem)
        {
            var currentuser = await usermanager.GetUserAsync(User);
            var successful = await fixitService.AddItemAsync(newitem, currentuser);
            if (!successful)
            {
                return BadRequest("Could not add this item");
            }
            return RedirectToAction("Index");
        }
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> MarkDone(Guid id)
        {
            if (id == Guid.Empty)
            {
                return RedirectToAction("Index");
            }
            var currentuser = await usermanager.GetUserAsync(User);
            var successful = await fixitService.MarkDoneAsync(id, currentuser);
            if (!successful)
            {
                return BadRequest("Could not mark item as done.");
            }

            return RedirectToAction("Index");
        }


    }
}

FixIt/Views/Shared/_AdminActionView.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<IdentityUser> signInManager
@inject UserManager<IdentityUser> usermanager
@if (signInManager.IsSignedIn(User))
{
    var currentuser = await usermanager.GetUserAsync(User);
    var isAdmin = currentuser != null && await usermanager.IsInRoleAsync(currentuser, "Administrator");
    if (isAdmin)
    {
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin</a>
        </li>
    }
    else
    {
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="" asp-action="">Admin(disabled)</a>
        </li>
    }
}

FixIt/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FixIt</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FixIt.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FixIt</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FixIt" asp-action="Index">Todo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <partial name="_AdminActionView" />
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - FixIt - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>